# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main', 'test-branch']
    pull_request:
        branches: ['main', 'test-branch']

env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    EMAIL: ${{github.event.pusher.email}}

jobs:
    build:
        name: Install Packages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: echo "$EMAIL"

            - name: Display Branch Name
              run:
                  echo "$BRANCH_NAME"

                  # ------ Commit Changes ------
            - name: Pull
              uses: EndBug/add-and-commit@v9
              with:
                  pull: '--rebase origin main'

            - name: Dummy write
              run: echo //commit  >> src/main.jsx;

            # ------ Commit Changes ------
            - name: Committing changes
              uses: EndBug/add-and-commit@v9
              with:
                  add: '.'
                  commit: --signoff
                  message: 'Built Lang File'
                  push: '-u origin ${{ github.head_ref || github.ref_name }}'

            - name: Yarn
              run: yarn

            - name: Build
              run: yarn build
